stages:
  - buildAndPush

docker-build:
  image: docker:latest
  stage: buildAndPush
  services:
    - docker:dind
  script:
    - docker build .
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile

docker-push:
  stage: buildAndPush
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - echo "gitlab-wrap_"$CI_COMMIT_TAG > /kaniko/version.txt
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/gitlab-wrap:$(cat /kaniko/version.txt)
  rules:
    - if: $CI_COMMIT_TAG != null

